// contexts/LanguageContext.tsx
'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'am';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Complete translations for all pages
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.departments': 'Departments',
    'nav.doctors': 'Doctors',
    'nav.gallery': 'Gallery',
    'nav.news': 'News',
    'nav.contact': 'Contact',
    
    // About dropdown
    'about.what': 'What is Afilas?',
    'about.vision': 'Our Vision/Mission',
    'about.values': 'Statement of Core Values',
    'about.board': 'Board of Directors',
    'about.specialists': 'Specialist Doctors',
    
    // Top bar
    'topbar.location': 'Bahir Dar, Ethiopia',
    'topbar.phone': '+251-58-320-1998/4167',
    'topbar.hours': 'Mon - Sun: 24 Hours',
    'topbar.hospital': 'Afilas General Hospital',
    'topbar.multispecialty': 'Multi-Specialty Hospital',
    'topbar.facilities': 'State-of-the-art Facilities',
    'topbar.doctors': '5+ Expert Doctors',
    'topbar.care': 'Compassionate Care',
    
    // Buttons
    'button.login': 'Login',
    'button.register': 'Register',
    'button.appointment': 'Book',
    'button.theme': 'Theme',
    'button.language': 'አማርኛ',
    'button.book': 'Book Appointment',
    'button.contact': 'Contact Us',
    'button.learn': 'Learn More',
    'button.view_all': 'View All',
    'button.submit': 'Submit',
    'button.sending': 'Sending...',
    'button.cancel': 'Cancel',
    'button.save': 'Save',
    'button.edit': 'Edit',
    'button.delete': 'Delete',
    'button.add': 'Add',
    'button.refresh': 'Refresh',
    'button.back': 'Back',
    'button.close': 'Close',
    'button.clear': 'Clear',
    'button.update': 'Update',
    'button.saving': 'Saving...',
    'button.retry': 'Retry',
    'button.back_to_home': 'Back to Home',
    'button.view_details': 'View Details',
    
    // Home page
    'home.title': 'Setting the standard in patient care',
    'home.subtitle': 'Four commitments that guide every department at Afilas.',
    'home.services': 'Our medical services',
    'home.services_desc': 'A snapshot of our specialty departments.',
    'home.team': 'Meet Our Team',
    'home.team_desc': 'Our specialist doctors are here to provide you with the best care.',
    'home.news': 'Latest news',
    'home.news_desc': 'Stay updated with our latest announcements',
    'home.hero_title': 'Welcome to Afilas Hospital',
    'home.hero_subtitle': 'The voice of knowledge is heard',
    'home.hero_desc': 'A multi-specialty hospital overlooking Lake Tana, offering state-of-the-art diagnostic and therapeutic care from more than ten specialty centers — in one stop.',
    'home.hero_title2': 'Advanced Medical Care',
    'home.hero_subtitle2': 'State-of-the-art facilities',
    'home.hero_desc2': 'Experience world-class healthcare with our modern equipment and cutting-edge medical technology.',
    'home.hero_title3': 'Your Health, Our Priority',
    'home.hero_subtitle3': 'Compassionate care, always',
    'home.hero_desc3': 'Our dedicated team of 75+ specialists is committed to providing personalized care.',
    
    // Values
    'value.patient_care': 'Patient care',
    'value.patient_care_desc': 'Compassionate, respectful, and quality care with safe handling for every patient who walks through our doors.',
    'value.modern_lab': 'Modern lab',
    'value.modern_lab_desc': 'Technologically advanced laboratory and imaging services, all under one roof.',
    'value.trusted_doctors': 'Trusted doctors',
    'value.trusted_doctors_desc': 'Competent, credible physicians with over 75 specialists and health professionals.',
    'value.availability': 'Availability',
    'value.availability_desc': 'We are here for you 24 hours a day, 7 days a week. Don\'t hesitate to visit us.',
    'value.compassion': 'Compassion',
    'value.compassion_desc': 'Provide the best care and treat patients and family members with sensitivity and empathy.',
    'value.integrity': 'Integrity',
    'value.integrity_desc': 'Adhere to the highest standards of professionalism, ethics and personal responsibility.',
    'value.quality': 'Quality of care',
    'value.quality_desc': 'Deliver the best outcomes and highest quality service through the dedicated effort of every team member.',
    'value.teamwork': 'Teamwork',
    'value.teamwork_desc': 'Value the contributions of all, blending the skills of individual staff members.',
    'value.safety': 'Patient & staff safety',
    'value.safety_desc': 'Safety shall never be compromised and nothing is more important than the safety of our patients and our staff.',
    'value.community': 'Community',
    'value.community_desc': 'We value meeting the vital responsibilities in the community we serve.',
    
    // About page
    'about.title': 'About Afilas',
    'about.subtitle': 'Built by scholars who lived the experiences of the community we serve.',
    'about.desc': 'Committed to providing compassionate, respectful, and high-quality healthcare to our community through innovative and dedicated service.',
    'about.what_title': 'What is Afilas?',
    'about.what_desc1': 'Afilas Pharmaceuticals Manufacturing and Medical Services S.C. was established in June 2017 by a group of committed, visionary, team-oriented health science scholars. The word "Afilas" was selected from the Saban language, meaning "the voice of scholars is heard" — a reminder that professional expertise should guide every practice.',
    'about.what_desc2': 'Our first business, Afilas Health Center, opened in January 2018 and grew into Afilas General Hospital (AGH), now one of the leading healthcare destinations in the Amhara National Regional State. In 2022 we opened Afilas Pharmaceuticals Wholesale, and in 2026 we opened the Afilas Diagnostics Center.',
    'about.vision_title': 'Vision',
    'about.vision_desc': 'Aspiring to provide the perfect patient experience through innovative and compassionate care in the region by 2030.',
    'about.mission_title': 'Mission',
    'about.mission_desc1': 'To provide cost effective, compassionate, respectful, and high quality healthcare to the community.',
    'about.mission_desc2': 'To offer highly equitable corporate social responsibility.',
    'about.mission_desc3': 'To enhance the culture of Employee engagement.',
    'about.mission_desc4': 'To promote Customer satisfaction, health and wellness.',
    
    // Departments page
    'dept.title': 'Our Medical Services',
    'dept.subtitle': 'More than twenty specialty centers under one roof, offering state-of-the-art diagnostic and therapeutic care.',
    'dept.specialized': 'Our Specialized Departments',
    'dept.description': 'Each department is equipped with modern technology and staffed by experienced specialists',
    'dept.learn': 'Learn More',
    'dept.cta': 'Need to Book an Appointment?',
    'dept.cta_text': 'Our team of specialists is ready to provide you with the best possible care. Schedule your appointment today.',
    'dept.book': 'Book an Appointment',
    'dept.contact': 'Contact Us',
    'dept.comprehensive_care': 'Comprehensive Care',
    'dept.default_summary': 'Comprehensive medical services provided by our specialist team.',
    'dept.error_load': 'Failed to load departments. Showing available data.',
    'dept.no_departments': 'No departments available yet.',
    'dept.check_back': 'Please check back later.',
    
    // Appointment page
    'appointment.title': 'Book Your Appointment',
    'appointment.subtitle': 'Fill in your details below and our staff will confirm your visit.',
    'appointment.personal': 'Personal Information',
    'appointment.fullname': 'Full name',
    'appointment.phone': 'Phone',
    'appointment.email': 'Email',
    'appointment.department': 'Department',
    'appointment.doctor': 'Doctor',
    'appointment.date': 'Date & Time',
    'appointment.choose': 'Choose date & time',
    'appointment.additional': 'Additional Information',
    'appointment.note': 'Any additional information...',
    'appointment.submit': 'Request Appointment',
    'appointment.submitting': 'Submitting...',
    'appointment.agree': 'By submitting, you agree to our terms and privacy policy.',
    'appointment.success': 'Thank You!',
    'appointment.success_msg': 'Your appointment request has been received. A confirmation email is on its way.',
    'appointment.steps': 'Check your email for confirmation',
    'appointment.steps2': 'Wait for staff to confirm',
    'appointment.steps3': 'Receive a reminder before your visit',
    'appointment.book_again': 'Book another appointment',
    'appointment.loading': 'Loading...',
    'appointment.error_load': 'Failed to load data. Please refresh the page.',
    'appointment.error_name': 'Please enter your full name',
    'appointment.error_email': 'Please enter your email address',
    'appointment.error_phone': 'Please enter your phone number',
    'appointment.error_department': 'Please select a department',
    'appointment.error_doctor': 'Please select a doctor',
    'appointment.error_date': 'Please select a date and time',
    'appointment.error_general': 'Something went wrong. Please try again.',
    'appointment.error': 'Error',
    'appointment.received': 'Request received',
    'appointment.next_steps': 'Next steps:',
    'appointment.step_info': 'Info',
    'appointment.step_dept': 'Dept',
    'appointment.step_confirm': 'Confirm',
    'appointment.department_doctor': 'Department & Doctor',
    'appointment.date_time': 'Date & Time',
    'appointment.name_placeholder': 'John Doe',
    'appointment.phone_placeholder': '+251 9XX XXX XXX',
    'appointment.email_placeholder': 'john@example.com',
    'appointment.select_department': 'Select department',
    'appointment.select_doctor': 'Select doctor',
    'appointment.no_doctors': 'No doctors available',
    
    // Contact page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Leave us a message',
    'contact.address': 'Bahir Dar, Kebele 13, around Felege Hiwot Hospital',
    'contact.emergency': 'Emergency',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.hours': 'Hours',
    'contact.open': 'Open 24 hours, every day',
    'contact.name': 'Your name',
    'contact.email_label': 'Your email',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.send': 'Send message',
    'contact.success': 'Message sent successfully!',
    'contact.address_label': 'Address',
    'contact.emergency_label': 'Emergency',
    'contact.phone_label': 'Phone',
    
    'contact.hours_label': 'Hours',
    'contact.send_message': 'Send us a message',
    'contact.error_general': 'Something went wrong. Please try again.',
    
    // Gallery page
    'gallery.title': 'A look inside Afilas',
    'gallery.desc': 'Explore our state-of-the-art facilities and compassionate care environment',
    'gallery.empty': 'No images in the gallery yet.',
    'gallery.check_back': 'Check back soon for updates.',
    'gallery.heading': 'A look inside Afilas',
    'gallery.description': 'Explore our state-of-the-art facilities and compassionate care environment',
    'gallery.loading': 'Loading gallery...',
    'gallery.error_load': 'Failed to load gallery images. Please refresh the page.',
    'gallery.retry': 'Retry',
    'gallery.video': 'Video',
    'gallery.image_not_available': 'Image not available',
    'gallery.untitled': 'Untitled',
    'gallery.showing': 'Showing',
    'gallery.item': 'item',
    'gallery.click_play': 'Click play to start',
    
    // Services page
    'services.search_placeholder': 'Search services...',
    'services.all_departments': 'All Departments',
    'services.loading': 'Loading services...',
    'services.error_load': 'Failed to load services. Please refresh the page.',
    'services.retry': 'Try Again',
    'services.no_services': 'No Services Found',
    'services.adjust_filters': 'Try adjusting your search or filter criteria.',
    'services.no_services_available': 'No services are currently available.',
    'services.service': 'service',
    'services.found': 'found',
    'services.no_image': 'No Image',
    'services.view_details': 'View Details',
    'services.description': 'Description',
    'services.no_description': 'No description available',
    'services.department': 'Department',
    'services.price': 'Price',
    'services.duration': 'Duration',
    'services.minutes': 'minutes',
    'services.status': 'Status',
    'services.active': 'Active',
    'services.inactive': 'Inactive',
    'services.book_appointment': 'Book Appointment',
    'services.unknown_department': 'Unknown Department',
    
    // News page
    'news.title': 'News & Tips',
    'news.heading': 'Our latest news',
    'news.empty': 'Articles will appear here once connected to the hospital database.',
    'news.date_pending': 'Date pending',
    
    // Doctors page
    'doctors.our_team': 'Our Team',
    'doctors.meet_our_doctors': 'Meet Our Doctors',
    'doctors.description': 'Our team of highly qualified and experienced specialists is dedicated to providing exceptional healthcare services.',
    'doctors.search_placeholder': 'Search doctors by name, specialty, or department...',
    'doctors.doctor': 'doctor',
    'doctors.error_load': 'Failed to load doctors. Please refresh the page.',
    'doctors.retry': 'Retry',
    'doctors.no_results': 'No doctors found matching your search.',
    'doctors.no_doctors': 'No doctors available yet.',
    'doctors.clear_search': 'Clear search',
    'doctors.experience': 'experience',
    'doctors.view_profile': 'View Profile',
    
    // Footer
    'footer.hospital': 'Afilas General Hospital',
    'footer.desc': '"Afilas" — the voice of knowledge is heard. Multi-specialty care in Bahir Dar, open every day, all day.',
    'footer.visit': 'Visit us',
    'footer.explore': 'Explore',
    'footer.admin': 'Administration',
    'footer.staff': 'Staff sign in',
    'footer.rights': 'All rights reserved.',
    'footer.address': 'Bahir Dar, Kebele 13, around Felege Hiwot Hospital',
    'footer.tel': 'Tel: +251-58-320-4167',
    'footer.email': 'Email: info@afilaspmms.com',
    'footer.open': 'Open 24 hours, every day',
    'footer.book_appointment': 'Book an appointment',
    'footer.staff_sign_in': 'Staff sign in',
    'footer.copyright': 'Afilas Pharmaceuticals Manufacturing and Medical Services S.C. All rights reserved.',
    
    // WebChat
    'webchat.chat_with_us': 'Chat with us',
    
    // Admin Dashboard
    'admin.dashboard': 'Dashboard',
    'admin.dashboard.welcome': "Welcome back! Here's what's happening with your hospital today.",
    'admin.dashboard.total_appointments': 'Total Appointments',
    'admin.dashboard.pending': 'Pending',
    'admin.dashboard.today_appointments': "Today's Appointments",
    'admin.dashboard.active_doctors': 'Active Doctors',
    'admin.dashboard.departments': 'Departments',
    'admin.dashboard.news_articles': 'News Articles',
    'admin.dashboard.upcoming_appointments': 'Upcoming Appointments',
    'admin.dashboard.no_upcoming': 'No upcoming appointments.',
    'admin.dashboard.patient': 'Patient',
    'admin.dashboard.department': 'Department',
    'admin.dashboard.date_time': 'Date & Time',
    'admin.dashboard.status': 'Status',
    
    // Admin Departments
    'admin.departments.title': 'Departments',
    'admin.departments.subtitle': 'Manage hospital departments and their details',
    'admin.departments.error_load': 'Failed to load data. Please refresh the page.',
    'admin.departments.deleted_success': 'Department deleted successfully!',
    'admin.departments.error_delete': 'Failed to delete department. Please try again.',
    'admin.departments.updated': 'Department updated successfully!',
    'admin.departments.created': 'Department created successfully!',
    'admin.departments.error_save': 'Failed to save department',
    'admin.departments.cannot_delete': 'Cannot Delete Department',
    'admin.departments.cannot_delete_name': 'Cannot delete',
    'admin.departments.has_relationships': 'This department has active relationships that must be resolved first:',
    'admin.departments.doctors_assigned': 'doctor(s) assigned',
    'admin.departments.services_assigned': 'service(s) assigned',
    'admin.departments.options': 'You can either:',
    'admin.departments.option1': 'Delete all doctors and services from this department first',
    'admin.departments.option2': 'Move them to another department',
    'admin.departments.option3': 'Force delete (will remove all associations)',
    'admin.departments.go_to_doctors': 'Go to Doctors',
    'admin.departments.go_to_services': 'Go to Services',
    'admin.departments.confirm_force_delete': '⚠️ This will remove all associations. Are you sure?',
    'admin.departments.deleting': 'Deleting...',
    'admin.departments.force_delete': 'Force Delete',
    'admin.departments.edit': 'Edit Department',
    'admin.departments.add': 'Add New Department',
    'admin.departments.name': 'Department Name',
    'admin.departments.name_placeholder': 'e.g., Cardiology',
    'admin.departments.name_amharic': 'Name in Amharic',
    'admin.departments.name_amharic_placeholder': 'e.g., የልብ ሕክምና',
    'admin.departments.slug': 'Slug (URL identifier)',
    'admin.departments.slug_placeholder': 'e.g., cardiology',
    'admin.departments.slug_hint': 'Leave empty to auto-generate from name',
    'admin.departments.summary': 'Summary',
    'admin.departments.summary_placeholder': 'Brief summary of the department...',
    'admin.departments.details': 'Details',
    'admin.departments.details_placeholder': 'Detailed description of the department and its services...',
    'admin.departments.saving': 'Saving...',
    'admin.departments.update': 'Update Department',
    'admin.departments.create': 'Create Department',
    'admin.departments.loading': 'Loading departments...',
    'admin.departments.no_departments': 'No Departments Found',
    'admin.departments.no_departments_hint': 'Click "Add Department" to create your first department.',
    'admin.departments.add_department': 'Add Department',
    'admin.departments.doctor': 'Doctor',
    'admin.departments.service': 'Service',
    'admin.departments.has_relations_tooltip': 'Department has assigned doctors or services',
    'admin.departments.delete_tooltip': 'Delete department',
    
    // Admin Doctors
    'admin.doctors.title': 'Doctors',
    'admin.doctors.subtitle': 'Manage your hospital doctors and specialists',
    'admin.doctors.error_no_token': 'Authentication token not found. Please login again.',
    'admin.doctors.error_session_expired': 'Your session has expired. Please log out and log in again.',
    'admin.doctors.error_upload_failed': 'Upload failed',
    'admin.doctors.error_no_url': 'No URL returned from upload',
    'admin.doctors.error_email_required': 'Email is required',
    'admin.doctors.error_upload_image': 'Failed to upload image. Please try again.',
    'admin.doctors.error_email_exists': 'A doctor with this email already exists. Please use a different email address.',
    'admin.doctors.error_save': 'Could not save doctor. Please try again.',
    'admin.doctors.error_delete': 'Failed to delete doctor. Please try again.',
    'admin.doctors.updated': 'Doctor updated successfully!',
    'admin.doctors.created': 'Doctor added successfully!',
    'admin.doctors.deleted': 'Doctor deleted successfully!',
    'admin.doctors.confirm_delete': 'Are you sure you want to delete this doctor?',
    'admin.doctors.add': 'Add Doctor',
    'admin.doctors.edit': 'Edit Doctor',
    'admin.doctors.add_new': 'Add New Doctor',
    'admin.doctors.upload_hint': 'Click the upload button to add a photo',
    'admin.doctors.full_name': 'Full Name',
    'admin.doctors.name_placeholder': 'Dr. John Doe',
    
    'admin.doctors.title_placeholder': 'e.g., Cardiologist, MD',
    'admin.doctors.email': 'Email',
    'admin.doctors.email_placeholder': 'doctor@hospital.com',
    'admin.doctors.phone': 'Phone',
    'admin.doctors.phone_placeholder': '+251 9XX XXX XXX',
    'admin.doctors.department': 'Department',
    'admin.doctors.select_department': 'Select a department',
    'admin.doctors.no_departments': 'No departments available. Please add a department first.',
    'admin.doctors.bio': 'Bio',
    'admin.doctors.bio_placeholder': 'Brief biography of the doctor...',
    'admin.doctors.saving': 'Saving...',
    'admin.doctors.update': 'Update Doctor',
    'admin.doctors.no_departments_warning': 'Please add a department first before creating a doctor.',
    'admin.doctors.loading': 'Loading doctors...',
    'admin.doctors.no_doctors': 'No Doctors Found',
    'admin.doctors.no_doctors_hint': 'Click "Add Doctor" to create your first doctor.',
    'admin.doctors.active': 'Active',
    'admin.doctors.inactive': 'Inactive',
    'admin.doctors.schedule_slots': 'schedule slots',
    'admin.doctors.showing': 'Showing',
    'admin.doctors.doctor': 'doctor',
    
    // Admin Appointments
    'admin.appointments.title': 'Appointments',
    'admin.appointments.subtitle': 'Manage all patient appointments',
    'admin.appointments.all_statuses': 'All statuses',
    'admin.appointments.loading': 'Loading appointments...',
    'admin.appointments.error_load': 'Failed to load appointments',
    'admin.appointments.error_update': 'Failed to update appointment status',
    'admin.appointments.error_delete': 'Failed to delete appointment',
    'admin.appointments.status_updated': 'Appointment status updated to',
    'admin.appointments.deleted': 'Appointment deleted successfully!',
    'admin.appointments.confirm_delete': 'Delete this appointment?',
    'admin.appointments.no_appointments': 'No appointments found.',
    'admin.appointments.no_filtered': 'No appointments with this status',
    'admin.appointments.no_created': 'No appointments have been created yet',
    'admin.appointments.patient': 'Patient',
    'admin.appointments.contact': 'Contact',
    'admin.appointments.department': 'Department',
    'admin.appointments.doctor': 'Doctor',
    'admin.appointments.date_time': 'Date & Time',
    'admin.appointments.status': 'Status',
    'admin.appointments.actions': 'Actions',
    'admin.appointments.not_assigned': 'Not assigned',
    'admin.appointments.reminder_sent': 'Reminder sent',
    'admin.appointments.showing': 'Showing',
    'admin.appointments.appointment': 'appointment',
    
    // Admin Gallery
    'admin.gallery.title': 'Gallery',
    'admin.gallery.subtitle': 'Manage hospital gallery images and videos',
    'admin.gallery.untitled': 'Untitled',
    'admin.gallery.error_load': 'Failed to load gallery. Please refresh the page.',
    'admin.gallery.error_invalid_url': 'Please enter a valid URL.',
    'admin.gallery.error_save': 'Could not save gallery item.',
    'admin.gallery.error_remove': 'Failed to remove item',
    'admin.gallery.updated': 'Gallery item updated successfully!',
    'admin.gallery.added': 'Gallery item added successfully!',
    'admin.gallery.removed': 'Item removed successfully!',
    'admin.gallery.confirm_delete': 'Remove this item?',
    'admin.gallery.default_title': 'Gallery Item',
    'admin.gallery.edit_item': 'Edit Gallery Item',
    'admin.gallery.add_item': 'Add Gallery Item',
    'admin.gallery.url_hint': 'Paste a hosted URL (e.g., from YouTube, Vimeo, Imgur, Cloudinary, or your storage provider).',
    'admin.gallery.type': 'Type',
    'admin.gallery.image': 'Image',
    'admin.gallery.video': 'Video',
    'admin.gallery.url': 'URL',
    'admin.gallery.video_placeholder': 'https://www.youtube.com/watch?v=...',
    'admin.gallery.image_placeholder': 'https://example.com/image.jpg',
    'admin.gallery.preview': 'Preview',
    'admin.gallery.video_preview': 'Video preview',
    'admin.gallery.title_label': 'Title',
    'admin.gallery.title_placeholder': 'Gallery item title',
    'admin.gallery.caption_label': 'Caption',
    'admin.gallery.caption_placeholder': 'Brief description',
    'admin.gallery.thumbnail_label': 'Thumbnail URL (optional)',
    'admin.gallery.thumbnail_placeholder': 'https://example.com/thumbnail.jpg',
    'admin.gallery.thumbnail_hint': 'For videos, you can provide a thumbnail image URL',
    'admin.gallery.loading': 'Loading gallery...',
    'admin.gallery.no_items': 'No Items in Gallery',
    'admin.gallery.no_items_hint': 'Add your first item using the form above.',
    'admin.gallery.gallery_item': 'Gallery item',
    'admin.gallery.invalid_url': 'Invalid URL',
    'admin.gallery.showing': 'Showing',
    'admin.gallery.item': 'item',
    'admin.gallery.refresh': 'Refresh gallery',
    'admin.gallery.gallery_image': 'Gallery image',
    'admin.gallery.open_new_tab': 'Open in new tab',
    
    // Admin News
    'admin.news.title': 'News',
    'admin.news.subtitle': 'Manage hospital news and announcements',
    'admin.news.add_article': 'Add Article',
    'admin.news.add_new_article': 'Add New Article',
    'admin.news.edit_article': 'Edit Article',
    'admin.news.updated': 'Article updated successfully!',
    'admin.news.added': 'Article added successfully!',
    'admin.news.deleted': 'Article deleted successfully!',
    'admin.news.error_save': 'Could not save article.',
    'admin.news.error_delete': 'Failed to delete article',
    'admin.news.confirm_delete': 'Delete this article?',
    'admin.news.title_label': 'Title',
    'admin.news.title_placeholder': 'Enter article title',
    'admin.news.category_label': 'Category',
    'admin.news.category_placeholder': 'e.g., News, Events, Updates',
    'admin.news.cover_image_label': 'Cover Image URL (optional)',
    'admin.news.cover_image_placeholder': 'https://example.com/image.jpg',
    'admin.news.excerpt_label': 'Excerpt',
    'admin.news.excerpt_placeholder': 'Brief summary of the article',
    'admin.news.content_label': 'Content',
    'admin.news.content_placeholder': 'Full article content...',
    'admin.news.published_label': 'Published',
    'admin.news.update_article': 'Update Article',
    'admin.news.loading': 'Loading articles...',
    'admin.news.no_articles': 'No Articles Found',
    'admin.news.no_articles_hint': 'Click "Add Article" to create your first news article.',
    'admin.news.draft': 'Draft',
    'admin.news.has_cover_image': 'Has cover image',
    'admin.news.showing': 'Showing',
    'admin.news.article': 'article',
    
    // Admin Services
    'admin.services.title': 'Services',
    'admin.services.subtitle': 'Manage hospital services with images',
    'admin.services.error_load': 'Failed to load data. Please refresh the page.',
    'admin.services.error_drop_image': 'Please drop an image file',
    'admin.services.error_save': 'Failed to save service',
    'admin.services.error_delete': 'Failed to delete service',
    'admin.services.updated': 'Service updated successfully!',
    'admin.services.created': 'Service created successfully!',
    'admin.services.deleted': 'Service deleted successfully!',
    'admin.services.confirm_delete': 'Delete this service?',
    'admin.services.add_service': 'Add Service',
    'admin.services.add_new_service': 'Add New Service',
    'admin.services.edit_service': 'Edit Service',
    'admin.services.update_service': 'Update Service',
    'admin.services.create_service': 'Create Service',
    'admin.services.service': 'service',
    'admin.services.service_image': 'Service Image',
    'admin.services.service_preview': 'Service preview',
    'admin.services.image_uploaded': 'Image uploaded',
    'admin.services.drag_drop': 'Drag & drop an image here, or click to browse',
    'admin.services.image_support': 'Supports JPG, PNG, GIF, WebP (Max 5MB)',
    'admin.services.choose_image': 'Choose Image',
    'admin.services.service_name': 'Service Name',
    'admin.services.service_name_placeholder': 'e.g., General Checkup',
    'admin.services.description': 'Description',
    'admin.services.description_placeholder': 'Describe the service...',
    'admin.services.department': 'Department',
    'admin.services.select_department': 'Select department',
    'admin.services.price': 'Price',
    'admin.services.price_placeholder': '0.00',
    'admin.services.duration': 'Duration (minutes)',
    'admin.services.duration_placeholder': '30',
    'admin.services.loading': 'Loading services...',
    'admin.services.no_services': 'No Services Found',
    'admin.services.no_services_hint': 'Click "Add Service" to create your first service.',
    'admin.services.active': 'Active',
    'admin.services.inactive': 'Inactive',
    'admin.services.min': 'min',
    
    // Admin Login
    'admin.login.admin_dashboard': 'Administrative Dashboard',
    'admin.login.staff_access': 'Staff Access',
    'admin.login.sign_in': 'Sign In',
    'admin.login.signing_in': 'Signing in...',
    'admin.login.email_address': 'Email Address',
    'admin.login.password': 'Password',
    'admin.login.password_placeholder': 'Enter your password',
    'admin.login.show_password': 'Show password',
    'admin.login.hide_password': 'Hide password',
    'admin.login.checking_backend': '⏳ Checking backend connection...',
    'admin.login.backend_offline': '⚠️ Backend server is not running. Please start it with:',
    'admin.login.error_backend_offline': '⚠️ Backend server is not running. Please start the backend first.',
    'admin.login.error_invalid_response': 'Invalid response from server. Please check the API response format.',
    'admin.login.error_connection': 'Cannot connect to backend. Please make sure it is running on http://localhost:5000',
    'admin.login.error_invalid_credentials': 'Invalid email or password. Please try again.',
    'admin.login.error_endpoint_not_found': 'Login endpoint not found. Please check the API URL.',
    'admin.login.error_general': 'Could not sign in. Please check your connection and try again.',
    
    // Admin Notifications
    'admin.notifications.title': 'Notifications',
    'admin.notifications.empty': 'No notifications',
    'admin.notifications.mark_all_read': 'Mark all as read',
    'admin.notifications.view_all': 'View all notifications',
  },
  am: {
    // Navigation
    'nav.home': 'መነሻ',
    'nav.about': 'ስለ እኛ',
    'nav.departments': 'ክፍሎች',
    'nav.doctors': 'ዶክተሮች',
    'nav.gallery': 'ምስሎች',
    'nav.news': 'ዜና',
    'nav.contact': 'አግኙን',
    
    // About dropdown
    'about.what': 'አፊላስ ምንድነው?',
    'about.vision': 'ራእያችን/ተልዕኳችን',
    'about.values': 'የመሠረታዊ እሴቶች መግለጫ',
    'about.board': 'የዳይሬክተሮች ቦርድ',
    'about.specialists': 'ልዩ ባለሙያ ዶክተሮች',
    
    // Top bar
    'topbar.location': 'ባህር ዳር፣ ኢትዮጵያ',
    'topbar.phone': '+251-58-320-1998/4167',
    'topbar.hours': 'ሰኞ - እሁድ: 24 ሰዓት',
    'topbar.hospital': 'አፊላስ አጠቃላይ ሆስፒታል',
    'topbar.multispecialty': 'ባለብዙ ስፔሻሊስት ሆስፒታል',
    'topbar.facilities': 'ዘመናዊ መገልገያዎች',
    'topbar.doctors': '5+ ልዩ ባለሙያ ዶክተሮች',
    'topbar.care': 'አዛኝ እንክብካቤ',
    
    // Buttons
    'button.login': 'ግባ',
    'button.register': 'ተመዝገብ',
    'button.appointment': 'ቀጠሮ',
    'button.theme': 'ገጽታ',
    'button.language': 'English',
    'button.book': 'ቀጠሮ ይያዙ',
    'button.contact': 'ያግኙን',
    'button.learn': 'ተጨማሪ ይወቁ',
    'button.view_all': 'ሁሉንም ይመልከቱ',
    'button.submit': 'ያስገቡ',
    'button.sending': 'በማስገባት ላይ...',
    'button.cancel': 'ይቅር',
    'button.save': 'ያስቀምጡ',
    'button.edit': 'ያስተካክሉ',
    'button.delete': 'ያጥፉ',
    'button.add': 'ያክሉ',
    'button.refresh': 'ያድሱ',
    'button.back': 'ወደ ኋላ',
    'button.close': 'ዝጋ',
    'button.clear': 'አጽዳ',
    'button.update': 'ያሻሽሉ',
    'button.saving': 'በማስቀመጥ ላይ...',
    'button.retry': 'እንደገና ይሞክሩ',
    'button.back_to_home': 'ወደ መነሻ ተመለስ',
    'button.view_details': 'ዝርዝሮችን ይመልከቱ',
    
    // Home page
    'home.title': 'የህመምተኛ እንክብካቤ ደረጃን ማስቀመጥ',
    'home.subtitle': 'በአፊላስ እያንዳንዱን ክፍል የሚመሩ አራት ቁርጠኝነቶች።',
    'home.services': 'የእኛ የህክምና አገልግሎቶች',
    'home.services_desc': 'የልዩ ልዩ ክፍሎቻችን ቅኝት።',
    'home.team': 'ቡድናችንን ይገናኙ',
    'home.team_desc': 'የባለሙያ ዶክተሮቻችን ለእርስዎ ምርጥ እንክብካቤ ለመስጠት እዚህ አሉ።',
    'home.news': 'የቅርብ ጊዜ ዜናዎች',
    'home.news_desc': 'በቅርብ ጊዜ ማስታወቂያዎቻችንን ይከታተሉ',
    'home.hero_title': 'እንኳን ወደ አፊላስ ሆስፒታል በደህና መጡ',
    'home.hero_subtitle': 'የእውቀት ድምጽ ተሰማ',
    'home.hero_desc': 'ታና ሐይቅን የሚያይ ባለብዙ ስፔሻሊስት ሆስፒታል፣ ከአስር በላይ ልዩ ልዩ ማዕከላት ዘመናዊ የምርመራ እና የህክምና አገልግሎት ይሰጣል።',
    'home.hero_title2': 'የላቀ የህክምና አገልግሎት',
    'home.hero_subtitle2': 'ዘመናዊ መገልገያዎች',
    'home.hero_desc2': 'በዘመናዊ መሳሪያዎች እና በቴክኖሎጂ የላቀ የጤና እንክብካቤ ይለማመዱ።',
    'home.hero_title3': 'ጤናዎ ቅድሚያችን ነው',
    'home.hero_subtitle3': 'ሁልጊዜ አዛኝ እንክብካቤ',
    'home.hero_desc3': '75+ ስፔሻሊስቶች ያሉት ቡድናችን ለእርስዎ ግላዊ እንክብካቤ ለመስጠት ቁርጠኛ ነው።',
    
    // Values
    'value.patient_care': 'የህመምተኛ እንክብካቤ',
    'value.patient_care_desc': 'ለእያንዳንዱ ህመምተኛ አዛኝ፣ አክባሪ እና ጥራት ያለው እንክብካቤ ከደህንነት ጋር።',
    'value.modern_lab': 'ዘመናዊ ላብራቶሪ',
    'value.modern_lab_desc': 'በቴክኖሎጂ የተራቀቁ የላብራቶሪ እና የምስል አገልግሎቶች፣ ሁሉም በአንድ ጣሪያ ስር።',
    'value.trusted_doctors': 'የታመኑ ዶክተሮች',
    'value.trusted_doctors_desc': 'ብቃት ያላቸው፣ እምነት የሚጣልባቸው ሐኪሞች ከ75 በላይ ስፔሻሊስቶች እና የጤና ባለሙያዎች ጋር።',
    'value.availability': 'መገኘት',
    'value.availability_desc': 'በሳምንቱ 7 ቀናት በ24 ሰዓት እዚህ ነን። እኛን ለመጠየቅ አያመንቱ።',
    'value.compassion': 'ርህራሄ',
    'value.compassion_desc': 'ለህመምተኞች እና ለቤተሰቦቻቸው ምርጥ እንክብካቤ እና አዛኝ አመለካከት መስጠት።',
    'value.integrity': 'ታማኝነት',
    'value.integrity_desc': 'ከፍተኛ የሙያዊ ባህሪ፣ ስነምግባር እና የግል ሃላፊነት ደረጃዎችን መከተል።',
    'value.quality': 'የእንክብካቤ ጥራት',
    'value.quality_desc': 'በእያንዳንዱ የቡድን አባል ቁርጠኝነት ምርጥ ውጤቶችን እና ከፍተኛ ጥራት ያለው አገልግሎት መስጠት።',
    'value.teamwork': 'የቡድን ስራ',
    'value.teamwork_desc': 'የሁሉንም አስተዋጾ ማድነቅ እና የግለሰብ ሰራተኞችን ክህሎት ማጣመር።',
    'value.safety': 'የህመምተኛ እና የሰራተኛ ደህንነት',
    'value.safety_desc': 'ደህንነት በጭራሽ አይጣስም እና ለአፊላስ ከህመምተኞች እና ሰራተኞች ደህንነት የበለጠ አስፈላጊ ነገር የለም።',
    'value.community': 'ማህበረሰብ',
    'value.community_desc': 'በምናገለግለው ማህበረሰብ ውስጥ ወሳኝ ሃላፊነቶችን መወጣት እና የህይወት ጥራትን እና ጤናን ለማሻሻል የመሪነት ሚና መውሰድ።',
    
    // About page
    'about.title': 'ስለ አፊላስ',
    'about.subtitle': 'የምናገለግለውን ማህበረሰብ ተሞክሮ በኖሩ ምሁራን የተገነባ።',
    'about.desc': 'በፈጠራ እና በታማኝ አገልግሎት ለማህበረሰባችን አዛኝ፣ አክባሪ እና ጥራት ያለው የጤና እንክብካቤ ለመስጠት ቁርጠኞች ነን።',
    'about.what_title': 'አፊላስ ምንድነው?',
    'about.what_desc1': 'አፊላስ ፋርማሲዩቲካልስ ማኑፋክቸሪንግ እና ሜዲካል ሰርቪስስ ኤስ.ሲ በጁን 2017 በቁርጠኝነት፣ ራዕይ ባላቸው፣ ቡድን-ተኮር የጤና ሳይንስ ምሁራን ቡድን ተቋቋመ። "አፊላስ" የሚለው ቃል ከሳባን ቋንቋ የተመረጠ ሲሆን ትርጉሙም "የእውቀት ድምጽ ተሰማ" ማለት ነው።',
    'about.what_desc2': 'የመጀመሪያው የንግድ ሥራችን የአፊላስ ጤና ማዕከል በጃንዋሪ 2018 ተከፈተ እና ወደ አፊላስ አጠቃላይ ሆስፒታል (ኤጂኤች) አደገ። በ2022 የአፊላስ ፋርማሲዩቲካልስ ጅምር ከፈትን እና በ2026 የአፊላስ ዲያግኖስቲክስ ማዕከልን ከፈትን።',
    'about.vision_title': 'ራዕይ',
    'about.vision_desc': 'በ2030 በክልሉ በፈጠራ እና በአዛኝ እንክብካቤ ፍጹም የሆነ የህመምተኛ ተሞክሮ ለመስጠት መጣር።',
    'about.mission_title': 'ተልዕኮ',
    'about.mission_desc1': 'ለማህበረሰብ ወጪ ቆጣቢ፣ አዛኝ፣ አክባሪ እና ጥራት ያለው የጤና እንክብካቤ መስጠት።',
    'about.mission_desc2': 'ከፍተኛ ፍትሃዊ የሆነ የኮርፖሬት ማህበራዊ ሃላፊነት መስጠት።',
    'about.mission_desc3': 'የሰራተኞች ተሳትፎ ባህልን ማሳደግ።',
    'about.mission_desc4': 'የደንበኞች እርካታ፣ ጤና እና ደህንነትን ማስተዋወቅ።',
    
    // Departments page
    'dept.title': 'የእኛ የህክምና አገልግሎቶች',
    'dept.subtitle': 'ከሃያ በላይ ልዩ ልዩ ማዕከላት በአንድ ጣሪያ ስር፣ ዘመናዊ የምርመራ እና የህክምና አገልግሎት ይሰጣሉ።',
    'dept.specialized': 'የእኛ ልዩ ልዩ ክፍሎች',
    'dept.description': 'እያንዳንዱ ክፍል በዘመናዊ ቴክኖሎጂ የታጠቀ እና ልምድ ባላቸው ስፔሻሊስቶች የሚመራ ነው',
    'dept.learn': 'ተጨማሪ ይወቁ',
    'dept.cta': 'ቀጠሮ መያዝ ያስፈልግዎታል?',
    'dept.cta_text': 'የባለሙያዎች ቡድናችን ለእርስዎ ምርጥ እንክብካቤ ለመስጠት ዝግጁ ነው። ዛሬውኑ ቀጠሮዎን ይያዙ።',
    'dept.book': 'ቀጠሮ ይያዙ',
    'dept.contact': 'ያግኙን',
    'dept.comprehensive_care': 'ሁሉን አቀፍ እንክብካቤ',
    'dept.default_summary': 'በባለሙያ ቡድናችን የሚሰጥ ሁሉን አቀፍ የህክምና አገልግሎት',
    'dept.error_load': 'ክፍሎችን መጫን አልተቻለም። ያለውን ውሂብ እያሳየን ነው።',
    'dept.no_departments': 'ምንም ክፍሎች የሉም',
    'dept.check_back': 'እባክዎ በኋላ ይመለሱ።',
    
    // Appointment page
    'appointment.title': 'ቀጠሮ ይያዙ',
    'appointment.subtitle': 'ዝርዝሮችዎን ይሙሉ እና ሰራተኞቻችን ጉብኝትዎን ያረጋግጣሉ።',
    'appointment.personal': 'የግል መረጃ',
    'appointment.fullname': 'ሙሉ ስም',
    'appointment.phone': 'ስልክ ቁጥር',
    'appointment.email': 'ኢሜይል',
    'appointment.department': 'ክፍል',
    'appointment.doctor': 'ዶክተር',
    'appointment.date': 'ቀን እና ሰዓት',
    'appointment.choose': 'ቀን እና ሰዓት ይምረጡ',
    'appointment.additional': 'ተጨማሪ መረጃ',
    'appointment.note': 'ተጨማሪ መረጃ ካለ...',
    'appointment.submit': 'ቀጠሮ ይጠይቁ',
    'appointment.submitting': 'በማስገባት ላይ...',
    'appointment.agree': 'በማስገባት ውሎቻችንን እና የግላዊነት ፖሊሲያችንን ይስማማሉ።',
    'appointment.success': 'እናመሰግናለን!',
    'appointment.success_msg': 'የቀጠሮ ጥያቄዎ ተቀብለናል። የማረጋገጫ ኢሜይል በመንገድ ላይ ነው።',
    'appointment.steps': 'ለማረጋገጫ ኢሜይልዎን ያረጋግጡ',
    'appointment.steps2': 'ሰራተኞች እስኪያረጋግጡ ይጠብቁ',
    'appointment.steps3': 'ከጉብኝትዎ በፊት ማሳሰቢያ ይደርስዎታል',
    'appointment.book_again': 'ሌላ ቀጠሮ ይያዙ',
    'appointment.loading': 'በማጫን ላይ...',
    'appointment.error_load': 'ውሂብ መጫን አልተቻለም። እባክዎ ገፁን ያድሱ።',
    'appointment.error_name': 'እባክዎ ሙሉ ስምዎን ያስገቡ',
    'appointment.error_email': 'እባክዎ ኢሜይል አድራሻዎን ያስገቡ',
    'appointment.error_phone': 'እባክዎ ስልክ ቁጥርዎን ያስገቡ',
    'appointment.error_department': 'እባክዎ ክፍል ይምረጡ',
    'appointment.error_doctor': 'እባክዎ ዶክተር ይምረጡ',
    'appointment.error_date': 'እባክዎ ቀን እና ሰዓት ይምረጡ',
    'appointment.error_general': 'የሆነ ስህተት ተከስቷል። እባክዎ እንደገና ይሞክሩ።',
    'appointment.error': 'ስህተት',
    'appointment.received': 'ጥያቄ ተቀብለናል',
    'appointment.next_steps': 'ቀጣይ እርምጃዎች:',
    'appointment.step_info': 'መረጃ',
    'appointment.step_dept': 'ክፍል',
    'appointment.step_confirm': 'አረጋግጥ',
    'appointment.department_doctor': 'ክፍል እና ዶክተር',
    'appointment.date_time': 'ቀን እና ሰዓት',
    'appointment.name_placeholder': 'ዮሐንስ ዶጎ',
    'appointment.phone_placeholder': '+251 9XX XXX XXX',
    'appointment.email_placeholder': 'john@example.com',
    'appointment.select_department': 'ክፍል ይምረጡ',
    'appointment.select_doctor': 'ዶክተር ይምረጡ',
    'appointment.no_doctors': 'ምንም ዶክተሮች የሉም',
    
    // Contact page
    'contact.title': 'ያግኙን',
    'contact.subtitle': 'መልዕክት ይላኩልን',
    'contact.address': 'ባህር ዳር፣ ቀበሌ 13፣ በፈለገ ህይወት ሆስፒታል አካባቢ',
    'contact.emergency': 'ድንገተኛ',
    'contact.phone': 'ስልክ',
    'contact.email': 'ኢሜይል',
    'contact.hours': 'የስራ ሰዓት',
    'contact.open': 'በሳምንቱ 7 ቀናት በ24 ሰዓት ክፍት ነን',
    'contact.name': 'ስምዎ',
    'contact.email_label': 'ኢሜይልዎ',
    'contact.subject': 'ርዕስ',
    'contact.message': 'መልዕክት',
    'contact.send': 'መልዕክት ይላኩ',
    'contact.success': 'መልዕክት በተሳካ ሁኔታ ተልኳል!',
    'contact.address_label': 'አድራሻ',
    'contact.emergency_label': 'ድንገተኛ',
    'contact.phone_label': 'ስልክ',
    
    'contact.hours_label': 'የስራ ሰዓት',
    'contact.send_message': 'መልዕክት ይላኩልን',
    'contact.error_general': 'የሆነ ስህተት ተከስቷል። እባክዎ እንደገና ይሞክሩ።',
    
    // Gallery page
    'gallery.title': 'የአፊላስ ውስጥ እይታ',
    'gallery.desc': 'ዘመናዊ መገልገያዎቻችንን እና አዛኝ የእንክብካቤ አካባቢያችንን ይመልከቱ',
    'gallery.empty': 'በጋለሪ ውስጥ ምስሎች የሉም።',
    'gallery.check_back': 'በቅርቡ ለዝማኔዎች ይመለሱ።',
    'gallery.heading': 'የአፊላስ ውስጥ እይታ',
    'gallery.description': 'ዘመናዊ መገልገያዎቻችንን እና አዛኝ የእንክብካቤ አካባቢያችንን ይመልከቱ',
    'gallery.loading': 'ጋለሪ በማጫን ላይ...',
    'gallery.error_load': 'የጋለሪ ምስሎችን መጫን አልተቻለም። እባክዎ ገፁን ያድሱ።',
    'gallery.retry': 'እንደገና ይሞክሩ',
    'gallery.video': 'ቪዲዮ',
    'gallery.image_not_available': 'ምስል አይገኝም',
    'gallery.untitled': 'ርዕስ የሌለው',
    'gallery.showing': 'እያሳየ ነው',
    'gallery.item': 'ነገር',
    'gallery.click_play': 'ለመጀመር እጫወት ይጫኑ',
    
    // Services page
    'services.search_placeholder': 'አገልግሎቶችን ፈልግ...',
    'services.all_departments': 'ሁሉም ክፍሎች',
    'services.loading': 'አገልግሎቶችን በማጫን ላይ...',
    'services.error_load': 'አገልግሎቶችን መጫን አልተቻለም። እባክዎ ገፁን ያድሱ።',
    'services.retry': 'እንደገና ይሞክሩ',
    'services.no_services': 'ምንም አገልግሎቶች አልተገኙም',
    'services.adjust_filters': 'እባክዎ ፍለጋዎን ወይም ማጣሪያዎችዎን ያስተካክሉ።',
    'services.no_services_available': 'በአሁኑ ጊዜ ምንም አገልግሎቶች የሉም።',
    'services.service': 'አገልግሎት',
    'services.found': 'ተገኝቷል',
    'services.no_image': 'ምስል የለም',
    'services.view_details': 'ዝርዝሮችን ይመልከቱ',
    'services.description': 'መግለጫ',
    'services.no_description': 'ምንም መግለጫ የለም',
    'services.department': 'ክፍል',
    'services.price': 'ዋጋ',
    'services.duration': 'ቆይታ',
    'services.minutes': 'ደቂቃዎች',
    'services.status': 'ሁኔታ',
    'services.active': 'ንቁ',
    'services.inactive': 'የማይንቀሳቀስ',
    'services.book_appointment': 'ቀጠሮ ይያዙ',
    'services.unknown_department': 'የማይታወቅ ክፍል',
    
    // News page
    'news.title': 'ዜና እና ምክሮች',
    'news.heading': 'የቅርብ ጊዜ ዜናዎቻችን',
    'news.empty': 'ከሆስፒታል ዳታቤዝ ጋር ከተገናኘ በኋላ መጣጥፎች እዚህ ይታያሉ።',
    'news.date_pending': 'ቀን በመጠባበቅ ላይ',
    
    // Doctors page
    'doctors.our_team': 'ቡድናችን',
    'doctors.meet_our_doctors': 'ዶክተሮቻችንን ይገናኙ',
    'doctors.description': 'ከፍተኛ ብቃት እና ልምድ ያላቸው የባለሙያዎች ቡድናችን ልዩ የጤና አገልግሎት ለመስጠት ቁርጠኛ ነው።',
    'doctors.search_placeholder': 'ዶክተሮችን በስም፣ በስፔሻሊቲ ወይም በክፍል ይፈልጉ...',
    'doctors.doctor': 'ዶክተር',
    'doctors.error_load': 'ዶክተሮችን መጫን አልተቻለም። እባክዎ ገፁን ያድሱ።',
    'doctors.retry': 'እንደገና ይሞክሩ',
    'doctors.no_results': 'ከፍለጋዎ ጋር የሚዛመዱ ዶክተሮች አልተገኙም።',
    'doctors.no_doctors': 'ምንም ዶክተሮች የሉም',
    'doctors.clear_search': 'ፍለጋን አጥፋ',
    'doctors.experience': 'ልምድ',
    'doctors.view_profile': 'መገለጫ ይመልከቱ',
    
    // Footer
    'footer.hospital': 'አፊላስ አጠቃላይ ሆስፒታል',
    'footer.desc': '"አፊላስ" — የእውቀት ድምጽ ተሰማ። በባህር ዳር ባለብዙ ስፔሻሊስት እንክብካቤ፣ በየቀኑ ክፍት ነው።',
    'footer.visit': 'ይጎብኙን',
    'footer.explore': 'ያስሱ',
    'footer.admin': 'አስተዳደር',
    'footer.staff': 'የሰራተኞች መግቢያ',
    'footer.rights': 'መብቶች በህግ የተጠበቁ ናቸው።',
    'footer.address': 'ባህር ዳር፣ ቀበሌ 13፣ በፈለገ ህይወት ሆስፒታል አካባቢ',
    'footer.tel': 'ስልክ: +251-58-320-4167',
    'footer.email': 'ኢሜይል: info@afilaspmms.com',
    'footer.open': 'በሳምንቱ 7 ቀናት በ24 ሰዓት ክፍት ነን',
    'footer.book_appointment': 'ቀጠሮ ይያዙ',
    'footer.staff_sign_in': 'የሰራተኞች መግቢያ',
    'footer.copyright': 'አፊላስ ፋርማሲዩቲካልስ ማኑፋክቸሪንግ እና ሜዲካል ሰርቪስስ ኤስ.ሲ መብቶች በህግ የተጠበቁ ናቸው።',
    
    // WebChat
    'webchat.chat_with_us': 'ከእኛ ጋር ይወያዩ',
    
    // Admin Dashboard
    'admin.dashboard': 'መቆጣጠሪያ ፓነል',
    'admin.dashboard.welcome': 'እንኳን በደህና መጡ! ዛሬ በሆስፒታልዎ ውስጥ የሚከሰተው ነገር እነሆ።',
    'admin.dashboard.total_appointments': 'ጠቅላላ ቀጠሮዎች',
    'admin.dashboard.pending': 'በመጠባበቅ ላይ',
    'admin.dashboard.today_appointments': 'የዛሬ ቀጠሮዎች',
    'admin.dashboard.active_doctors': 'ንቁ ዶክተሮች',
    'admin.dashboard.departments': 'ክፍሎች',
    'admin.dashboard.news_articles': 'የዜና መጣጥፎች',
    'admin.dashboard.upcoming_appointments': 'ቀጣይ ቀጠሮዎች',
    'admin.dashboard.no_upcoming': 'ምንም ቀጣይ ቀጠሮዎች የሉም።',
    'admin.dashboard.patient': 'ህመምተኛ',
    'admin.dashboard.department': 'ክፍል',
    'admin.dashboard.date_time': 'ቀን እና ሰዓት',
    'admin.dashboard.status': 'ሁኔታ',
    
    // Admin Departments
    'admin.departments.title': 'ክፍሎች',
    'admin.departments.subtitle': 'የሆስፒታል ክፍሎችን እና ዝርዝሮቻቸውን ያስተዳድሩ',
    'admin.departments.error_load': 'ውሂብ መጫን አልተቻለም። እባክዎ ገፁን ያድሱ።',
    'admin.departments.deleted_success': 'ክፍል በተሳካ ሁኔታ ተሰርዟል!',
    'admin.departments.error_delete': 'ክፍልን መሰረዝ አልተቻለም። እባክዎ እንደገና ይሞክሩ።',
    'admin.departments.updated': 'ክፍል በተሳካ ሁኔታ ተሻሽሏል!',
    'admin.departments.created': 'ክፍል በተሳካ ሁኔታ ተፈጥሯል!',
    'admin.departments.error_save': 'ክፍልን ማስቀመጥ አልተቻለም',
    'admin.departments.cannot_delete': 'ክፍልን መሰረዝ አይቻልም',
    'admin.departments.cannot_delete_name': 'መሰረዝ አይቻልም',
    'admin.departments.has_relationships': 'ይህ ክፍል መጀመሪያ መፈታት ያለባቸው ግንኙነቶች አሉት፡',
    'admin.departments.doctors_assigned': 'ዶክተር(ዎች) ተመድበዋል',
    'admin.departments.services_assigned': 'አገልግሎት(ዎች) ተመድበዋል',
    'admin.departments.options': 'እርስዎ ወይም፡',
    'admin.departments.option1': 'በመጀመሪያ ሁሉንም ዶክተሮች እና አገልግሎቶች ከዚህ ክፍል ይሰርዙ',
    'admin.departments.option2': 'ወደ ሌላ ክፍል ያዛውሩ',
    'admin.departments.option3': 'በግዳጅ ሰርዝ (ሁሉንም ግንኙነቶች ያስወግዳል)',
    'admin.departments.go_to_doctors': 'ወደ ዶክተሮች ይሂዱ',
    'admin.departments.go_to_services': 'ወደ አገልግሎቶች ይሂዱ',
    'admin.departments.confirm_force_delete': '⚠️ ይህ ሁሉንም ግንኙነቶች ያስወግዳል። እርግጠኛ ነዎት?',
    'admin.departments.deleting': 'በመሰረዝ ላይ...',
    'admin.departments.force_delete': 'በግዳጅ ሰርዝ',
    'admin.departments.edit': 'ክፍል ያስተካክሉ',
    'admin.departments.add': 'አዲስ ክፍል ያክሉ',
    'admin.departments.name': 'የክፍል ስም',
    'admin.departments.name_placeholder': 'ለምሳሌ ካርዲዮሎጂ',
    'admin.departments.name_amharic': 'ስም በአማርኛ',
    'admin.departments.name_amharic_placeholder': 'ለምሳሌ የልብ ሕክምና',
    'admin.departments.slug': 'Slug (የURL መለያ)',
    'admin.departments.slug_placeholder': 'ለምሳሌ cardiology',
    'admin.departments.slug_hint': 'ከስም ራስ-ሰር ለማመንጨት ባዶ ይተውት',
    'admin.departments.summary': 'ማጠቃለያ',
    'admin.departments.summary_placeholder': 'የክፍሉ አጭር መግለጫ...',
    'admin.departments.details': 'ዝርዝሮች',
    'admin.departments.details_placeholder': 'የክፍሉ እና የአገልግሎቶቹ ዝርዝር መግለጫ...',
    'admin.departments.saving': 'በማስቀመጥ ላይ...',
    'admin.departments.update': 'ክፍል ያሻሽሉ',
    'admin.departments.create': 'ክፍል ይፍጠሩ',
    'admin.departments.loading': 'ክፍሎችን በማጫን ላይ...',
    'admin.departments.no_departments': 'ምንም ክፍሎች አልተገኙም',
    'admin.departments.no_departments_hint': 'የመጀመሪያ ክፍልዎን ለመፍጠር "ክፍል ያክሉ" ን ጠቅ ያድርጉ።',
    'admin.departments.add_department': 'ክፍል ያክሉ',
    'admin.departments.doctor': 'ዶክተር',
    'admin.departments.service': 'አገልግሎት',
    'admin.departments.has_relations_tooltip': 'ክፍሉ የተመደቡ ዶክተሮች ወይም አገልግሎቶች አሉት',
    'admin.departments.delete_tooltip': 'ክፍል ሰርዝ',
    
    // Admin Doctors
    'admin.doctors.title': 'ዶክተሮች',
    'admin.doctors.subtitle': 'የሆስፒታልዎን ዶክተሮች እና ስፔሻሊስቶች ያስተዳድሩ',
    'admin.doctors.error_no_token': 'የማረጋገጫ ቶከን አልተገኘም። እባክዎ እንደገና ይግቡ።',
    'admin.doctors.error_session_expired': 'ክፍለ-ጊዜዎ አልቋል። እባክዎ ውጣ ወጥተው እንደገና ይግቡ።',
    'admin.doctors.error_upload_failed': 'ስዕል መጫን አልተቻለም',
    'admin.doctors.error_no_url': 'ከመጫኛ ምንም ዩአርኤል አልተገኘም',
    'admin.doctors.error_email_required': 'ኢሜይል ያስፈልጋል',
    'admin.doctors.error_upload_image': 'ስዕል መጫን አልተቻለም። እባክዎ እንደገና ይሞክሩ።',
    'admin.doctors.error_email_exists': 'በዚህ ኢሜይል ያለ ዶክተር አለ። እባክዎ ሌላ የኢሜይል አድራሻ ይጠቀሙ።',
    'admin.doctors.error_save': 'ዶክተርን ማስቀመጥ አልተቻለም። እባክዎ እንደገና ይሞክሩ።',
    'admin.doctors.error_delete': 'ዶክተርን መሰረዝ አልተቻለም። እባክዎ እንደገና ይሞክሩ።',
    'admin.doctors.updated': 'ዶክተር በተሳካ ሁኔታ ተሻሽሏል!',
    'admin.doctors.created': 'ዶክተር በተሳካ ሁኔታ ተጨምሯል!',
    'admin.doctors.deleted': 'ዶክተር በተሳካ ሁኔታ ተሰርዟል!',
    'admin.doctors.confirm_delete': 'ይህን ዶክተር መሰረዝ እንደሚፈልጉ እርግጠኛ ነዎት?',
    'admin.doctors.add': 'ዶክተር ያክሉ',
    'admin.doctors.edit': 'ዶክተር ያስተካክሉ',
    'admin.doctors.add_new': 'አዲስ ዶክተር ያክሉ',
    'admin.doctors.upload_hint': 'ፎቶ ለመጨመር የመጫኛ ቁልፍን ጠቅ ያድርጉ',
    'admin.doctors.full_name': 'ሙሉ ስም',
    'admin.doctors.name_placeholder': 'ዶ/ር ጆን ዶ',
    
    'admin.doctors.title_placeholder': 'ለምሳሌ የልብ ሐኪም፣ ኤምዲ',
    'admin.doctors.email': 'ኢሜይል',
    'admin.doctors.email_placeholder': 'doctor@hospital.com',
    'admin.doctors.phone': 'ስልክ',
    'admin.doctors.phone_placeholder': '+251 9XX XXX XXX',
    'admin.doctors.department': 'ክፍል',
    'admin.doctors.select_department': 'ክፍል ይምረጡ',
    'admin.doctors.no_departments': 'ምንም ክፍሎች የሉም። እባክዎ በመጀመሪያ ክፍል ያክሉ።',
    'admin.doctors.bio': 'የህይወት ታሪክ',
    'admin.doctors.bio_placeholder': 'የዶክተሩ አጭር የህይወት ታሪክ...',
    'admin.doctors.saving': 'በማስቀመጥ ላይ...',
    'admin.doctors.update': 'ዶክተር ያሻሽሉ',
    'admin.doctors.no_departments_warning': 'ዶክተር ከመፍጠርዎ በፊት እባክዎ ክፍል ያክሉ።',
    'admin.doctors.loading': 'ዶክተሮችን በማጫን ላይ...',
    'admin.doctors.no_doctors': 'ምንም ዶክተሮች አልተገኙም',
    'admin.doctors.no_doctors_hint': 'የመጀመሪያ ዶክተርዎን ለመፍጠር "ዶክተር ያክሉ" ን ጠቅ ያድርጉ።',
    'admin.doctors.active': 'ንቁ',
    'admin.doctors.inactive': 'የማይንቀሳቀስ',
    'admin.doctors.schedule_slots': 'የመርሃ ግብር ክፍተቶች',
    'admin.doctors.showing': 'እያሳየ ነው',
    'admin.doctors.doctor': 'ዶክተር',
    
    // Admin Appointments
    'admin.appointments.title': 'ቀጠሮዎች',
    'admin.appointments.subtitle': 'ሁሉንም የህመምተኞች ቀጠሮዎች ያስተዳድሩ',
    'admin.appointments.all_statuses': 'ሁሉም ሁኔታዎች',
    'admin.appointments.loading': 'ቀጠሮዎችን በማጫን ላይ...',
    'admin.appointments.error_load': 'ቀጠሮዎችን መጫን አልተቻለም',
    'admin.appointments.error_update': 'የቀጠሮ ሁኔታ መቀየር አልተቻለም',
    'admin.appointments.error_delete': 'ቀጠሮን መሰረዝ አልተቻለም',
    'admin.appointments.status_updated': 'የቀጠሮ ሁኔታ ተቀይሯል ወደ',
    'admin.appointments.deleted': 'ቀጠሮ በተሳካ ሁኔታ ተሰርዟል!',
    'admin.appointments.confirm_delete': 'ይህን ቀጠሮ ይሰርዙ?',
    'admin.appointments.no_appointments': 'ምንም ቀጠሮዎች አልተገኙም።',
    'admin.appointments.no_filtered': 'በዚህ ሁኔታ ምንም ቀጠሮዎች የሉም',
    'admin.appointments.no_created': 'እስካሁን ምንም ቀጠሮዎች አልተፈጠሩም',
    'admin.appointments.patient': 'ህመምተኛ',
    'admin.appointments.contact': 'እውቂያ',
    'admin.appointments.department': 'ክፍል',
    'admin.appointments.doctor': 'ዶክተር',
    'admin.appointments.date_time': 'ቀን እና ሰዓት',
    'admin.appointments.status': 'ሁኔታ',
    'admin.appointments.actions': 'ድርጊቶች',
    'admin.appointments.not_assigned': 'አልተመደበም',
    'admin.appointments.reminder_sent': 'ማሳሰቢያ ተልኳል',
    'admin.appointments.showing': 'እያሳየ ነው',
    'admin.appointments.appointment': 'ቀጠሮ',
    
    // Admin Gallery
    'admin.gallery.title': 'ጋለሪ',
    'admin.gallery.subtitle': 'የሆስፒታል ጋለሪ ምስሎችን እና ቪዲዮዎችን ያስተዳድሩ',
    'admin.gallery.untitled': 'ርዕስ የሌለው',
    'admin.gallery.error_load': 'ጋለሪ መጫን አልተቻለም። እባክዎ ገፁን ያድሱ።',
    'admin.gallery.error_invalid_url': 'እባክዎ ትክክለኛ ዩአርኤል ያስገቡ።',
    'admin.gallery.error_save': 'የጋለሪ ነገር ማስቀመጥ አልተቻለም።',
    'admin.gallery.error_remove': 'ነገር ማስወገድ አልተቻለም',
    'admin.gallery.updated': 'የጋለሪ ነገር በተሳካ ሁኔታ ተሻሽሏል!',
    'admin.gallery.added': 'የጋለሪ ነገር በተሳካ ሁኔታ ተጨምሯል!',
    'admin.gallery.removed': 'ነገር በተሳካ ሁኔታ ተወግዷል!',
    'admin.gallery.confirm_delete': 'ይህን ነገር ያስወግዱ?',
    'admin.gallery.default_title': 'የጋለሪ ነገር',
    'admin.gallery.edit_item': 'የጋለሪ ነገር ያስተካክሉ',
    'admin.gallery.add_item': 'የጋለሪ ነገር ያክሉ',
    'admin.gallery.url_hint': 'የተስተናገደ ዩአርኤል ይለጥፉ (ለምሳሌ ከ YouTube፣ Vimeo፣ Imgur፣ Cloudinary፣ ወይም የማከማቻ አቅራቢዎት)።',
    'admin.gallery.type': 'አይነት',
    'admin.gallery.image': 'ምስል',
    'admin.gallery.video': 'ቪዲዮ',
    'admin.gallery.url': 'ዩአርኤል',
    'admin.gallery.video_placeholder': 'https://www.youtube.com/watch?v=...',
    'admin.gallery.image_placeholder': 'https://example.com/image.jpg',
    'admin.gallery.preview': 'ቅድመ-እይታ',
    'admin.gallery.video_preview': 'የቪዲዮ ቅድመ-እይታ',
    'admin.gallery.title_label': 'ርዕስ',
    'admin.gallery.title_placeholder': 'የጋለሪ ነገር ርዕስ',
    'admin.gallery.caption_label': 'መግለጫ',
    'admin.gallery.caption_placeholder': 'አጭር መግለጫ',
    'admin.gallery.thumbnail_label': 'የምስል ማጠቃለያ ዩአርኤል (አማራጭ)',
    'admin.gallery.thumbnail_placeholder': 'https://example.com/thumbnail.jpg',
    'admin.gallery.thumbnail_hint': 'ለቪዲዮዎች፣ የምስል ማጠቃለያ ዩአርኤል ማቅረብ ይችላሉ',
    'admin.gallery.loading': 'ጋለሪ በማጫን ላይ...',
    'admin.gallery.no_items': 'በጋለሪ ውስጥ ምንም ነገሮች የሉም',
    'admin.gallery.no_items_hint': 'ከላይ ባለው ቅጽ የመጀመሪያ ነገርዎን ያክሉ።',
    'admin.gallery.gallery_item': 'የጋለሪ ነገር',
    'admin.gallery.invalid_url': 'ልክ ያልሆነ ዩአርኤል',
    'admin.gallery.showing': 'እያሳየ ነው',
    'admin.gallery.item': 'ነገር',
    'admin.gallery.refresh': 'ጋለሪ ያድሱ',
    'admin.gallery.gallery_image': 'የጋለሪ ምስል',
    'admin.gallery.open_new_tab': 'በአዲስ ትር ይክፈቱ',
    
    // Admin News
    'admin.news.title': 'ዜና',
    'admin.news.subtitle': 'የሆስፒታል ዜናዎችን እና ማስታወቂያዎችን ያስተዳድሩ',
    'admin.news.add_article': 'መጣጥፍ ያክሉ',
    'admin.news.add_new_article': 'አዲስ መጣጥፍ ያክሉ',
    'admin.news.edit_article': 'መጣጥፍ ያስተካክሉ',
    'admin.news.updated': 'መጣጥፍ በተሳካ ሁኔታ ተሻሽሏል!',
    'admin.news.added': 'መጣጥፍ በተሳካ ሁኔታ ተጨምሯል!',
    'admin.news.deleted': 'መጣጥፍ በተሳካ ሁኔታ ተሰርዟል!',
    'admin.news.error_save': 'መጣጥፍ ማስቀመጥ አልተቻለም።',
    'admin.news.error_delete': 'መጣጥፍ መሰረዝ አልተቻለም',
    'admin.news.confirm_delete': 'ይህን መጣጥፍ ይሰርዙ?',
    'admin.news.title_label': 'ርዕስ',
    'admin.news.title_placeholder': 'የመጣጥፍ ርዕስ ያስገቡ',
    'admin.news.category_label': 'ምድብ',
    'admin.news.category_placeholder': 'ለምሳሌ ዜና፣ ዝግጅቶች፣ ዝማኔዎች',
    'admin.news.cover_image_label': 'የሽፋን ምስል ዩአርኤል (አማራጭ)',
    'admin.news.cover_image_placeholder': 'https://example.com/image.jpg',
    'admin.news.excerpt_label': 'ማጠቃለያ',
    'admin.news.excerpt_placeholder': 'የመጣጥፉ አጭር ማጠቃለያ',
    'admin.news.content_label': 'ይዘት',
    'admin.news.content_placeholder': 'ሙሉ የመጣጥፍ ይዘት...',
    'admin.news.published_label': 'ታትሟል',
    'admin.news.update_article': 'መጣጥፍ ያሻሽሉ',
    'admin.news.loading': 'መጣጥፎችን በማጫን ላይ...',
    'admin.news.no_articles': 'ምንም መጣጥፎች አልተገኙም',
    'admin.news.no_articles_hint': 'የመጀመሪያ ዜና መጣጥፍዎን ለመፍጠር "መጣጥፍ ያክሉ" ን ጠቅ ያድርጉ።',
    'admin.news.draft': 'ረቂቅ',
    'admin.news.has_cover_image': 'የሽፋን ምስል አለው',
    'admin.news.showing': 'እያሳየ ነው',
    'admin.news.article': 'መጣጥፍ',
    
    // Admin Services
    'admin.services.title': 'አገልግሎቶች',
    'admin.services.subtitle': 'አገልግሎቶችን በምስሎች ያስተዳድሩ',
    'admin.services.error_load': 'ውሂብ መጫን አልተቻለም። እባክዎ ገፁን ያድሱ።',
    'admin.services.error_drop_image': 'እባክዎ የምስል ፋይል ይጣሉ',
    'admin.services.error_save': 'አገልግሎት ማስቀመጥ አልተቻለም',
    'admin.services.error_delete': 'አገልግሎት መሰረዝ አልተቻለም',
    'admin.services.updated': 'አገልግሎት በተሳካ ሁኔታ ተሻሽሏል!',
    'admin.services.created': 'አገልግሎት በተሳካ ሁኔታ ተፈጥሯል!',
    'admin.services.deleted': 'አገልግሎት በተሳካ ሁኔታ ተሰርዟል!',
    'admin.services.confirm_delete': 'ይህን አገልግሎት ይሰርዙ?',
    'admin.services.add_service': 'አገልግሎት ያክሉ',
    'admin.services.add_new_service': 'አዲስ አገልግሎት ያክሉ',
    'admin.services.edit_service': 'አገልግሎት ያስተካክሉ',
    'admin.services.update_service': 'አገልግሎት ያሻሽሉ',
    'admin.services.create_service': 'አገልግሎት ይፍጠሩ',
    'admin.services.service': 'አገልግሎት',
    'admin.services.service_image': 'የአገልግሎት ምስል',
    'admin.services.service_preview': 'የአገልግሎት ቅድመ-እይታ',
    'admin.services.image_uploaded': 'ምስል ተጭኗል',
    'admin.services.drag_drop': 'ምስል ይጎትቱ እና ይጣሉ፣ ወይም ለማሰስ ጠቅ ያድርጉ',
    'admin.services.image_support': 'JPG፣ PNG፣ GIF፣ WebP ይደግፋል (ከፍተኛ 5MB)',
    'admin.services.choose_image': 'ምስል ይምረጡ',
    'admin.services.service_name': 'የአገልግሎት ስም',
    'admin.services.service_name_placeholder': 'ለምሳሌ አጠቃላይ ምርመራ',
    'admin.services.description': 'መግለጫ',
    'admin.services.description_placeholder': 'አገልግሎቱን ይግለጹ...',
    'admin.services.department': 'ክፍል',
    'admin.services.select_department': 'ክፍል ይምረጡ',
    'admin.services.price': 'ዋጋ',
    'admin.services.price_placeholder': '0.00',
    'admin.services.duration': 'ቆይታ (ደቂቃዎች)',
    'admin.services.duration_placeholder': '30',
    'admin.services.loading': 'አገልግሎቶችን በማጫን ላይ...',
    'admin.services.no_services': 'ምንም አገልግሎቶች አልተገኙም',
    'admin.services.no_services_hint': 'የመጀመሪያ አገልግሎትዎን ለመፍጠር "አገልግሎት ያክሉ" ን ጠቅ ያድርጉ።',
    'admin.services.active': 'ንቁ',
    'admin.services.inactive': 'የማይንቀሳቀስ',
    'admin.services.min': 'ደቂቃ',
    
    // Admin Login
    'admin.login.admin_dashboard': 'የአስተዳደር መቆጣጠሪያ ፓነል',
    'admin.login.staff_access': 'የሰራተኞች መግቢያ',
    'admin.login.sign_in': 'ግባ',
    'admin.login.signing_in': 'በመግባት ላይ...',
    'admin.login.email_address': 'ኢሜይል አድራሻ',
    'admin.login.password': 'የይለፍ ቃል',
    'admin.login.password_placeholder': 'የይለፍ ቃልዎን ያስገቡ',
    'admin.login.show_password': 'የይለፍ ቃል አሳይ',
    'admin.login.hide_password': 'የይለፍ ቃል ደብቅ',
    'admin.login.checking_backend': '⏳ የተመለስ ግንኙነት በመፈተሽ ላይ...',
    'admin.login.backend_offline': '⚠️ የተመለስ አገልጋይ አይሰራም። እባክዎ በሚከተለው ይጀምሩት፡',
    'admin.login.error_backend_offline': '⚠️ የተመለስ አገልጋይ አይሰራም። እባክዎ በመጀመሪያ ያስጀምሩት።',
    'admin.login.error_invalid_response': 'ከአገልጋዩ ልክ ያልሆነ ምላሽ። እባክዎ የኤፒአይ ምላሽ ቅርጸት ያረጋግጡ።',
    'admin.login.error_connection': 'ወደ ተመለስ መገናኘት አልተቻለም። እባክዎ http://localhost:5000 ላይ መስራቱን ያረጋግጡ።',
    'admin.login.error_invalid_credentials': 'ልክ ያልሆነ ኢሜይል ወይም የይለፍ ቃል። እባክዎ እንደገና ይሞክሩ።',
    'admin.login.error_endpoint_not_found': 'የመግቢያ መዳረሻ አልተገኘም። እባክዎ የኤፒአይ ዩአርኤል ያረጋግጡ።',
    'admin.login.error_general': 'መግባት አልተቻለም። እባክዎ ግንኙነትዎን ያረጋግጡ እና እንደገና ይሞክሩ።',
    
    // Admin Notifications
    'admin.notifications.title': 'ማሳሰቢያዎች',
    'admin.notifications.empty': 'ምንም ማሳሰቢያዎች የሉም',
    'admin.notifications.mark_all_read': 'ሁሉንም እንደተነበበ ምልክት አድርግ',
    'admin.notifications.view_all': 'ሁሉንም ማሳሰቢያዎች ይመልከቱ',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved && (saved === 'en' || saved === 'am')) {
      setLanguage(saved);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'am' : 'en');
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}